### ISSUE TITLE
Yakuza 5 CFC not compiling

### ISSUE THREAD

**Issue by Mi-nk** [HeartlessSeph/FighterCommander#2]
It does however work when it is forced to always be CFC (Timo found that out)

> #File Rebuild
> else:
> 	stringlist = []
> 	stringpointerdict = OrderedDict()#Stores location of Strings written to file
> 	curdir =  os.getcwd()
> 	workdir = sys.argv[1]
> 	for f in os.listdir(kfile):#Gets file version
> 		curfile = workdir + "\\" + f
> 		with open(curfile, 'r', encoding='utf8') as file:
> 			jsonfile = json.load(file)
> 			fileversion = jsonfile["File Version"]
> 			tempkey = list(jsonfile.keys())[1]
> 			if "Old Engine Game" in jsonfile:
> 				enginegame = jsonfile["Old Engine Game"]
> 			elif "Hact ID" in jsonfile[tempkey]:
> 				filetype = "CHP"
> 			else:
> 				filetype = "CFC"
> 				enginegame = 0
**> 	filetype= "CFC"**

**Comment by HeartlessSeph** [comment]
Merged Timo's pull request fixing the issue.
